# Generated by Django 4.1.1 on 2022-12-12 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('email', models.EmailField(max_length=125)),
                ('DOB', models.DateField(max_length=8, null=True)),
                ('Age', models.IntegerField(null=True)),
                ('Mobile_Number', models.IntegerField(null=True)),
                ('gender', models.TextField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')])),
                ('Address', models.CharField(max_length=500, verbose_name='Address')),
                ('pin_code', models.CharField(max_length=6, verbose_name='Pincode')),
                ('purpose', models.TextField(choices=[('Enquiry', 'Enquiry'), ('Place Order', 'Place Order'), ('Return ', 'Return '), ('Replacement', 'Replacement')], null=True)),
                ('Materials_Provided', models.CharField(max_length=100, null=True)),
                ('courses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.courses')),
                ('departments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.departments')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='departments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.departments'),
        ),
    ]
